# Generated by Django 5.2.3 on 2025-07-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillswapapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='created_at',
        ),
        migrations.AddField(
            model_name='skill',
            name='availability',
            field=models.CharField(blank=True, help_text='E.g. Weekends, Evenings, etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, choices=[('music', 'Music'), ('language', 'Language'), ('tech', 'Technology'), ('art', 'Art'), ('sports', 'Sports'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='location',
            field=models.CharField(blank=True, help_text='Optional if the skill is remote', max_length=100, null=True),
        ),
    ]
