# Generated by Django 5.2.4 on 2025-07-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillswapapp', '0002_remove_skill_created_at_skill_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('offer', 'Offering Skill'), ('seek', 'Seeking Skill')], default='offer', help_text='*', max_length=10),
        ),
        migrations.AlterField(
            model_name='skill',
            name='availability',
            field=models.CharField(default='offer', help_text='* E.g. Weekends, Evenings etc.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('language', 'Language'), ('tech', 'Technology'), ('art', 'Art'), ('sports', 'Sports'), ('other', 'Other')], default='other', help_text='*', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='description',
            field=models.TextField(help_text='*', max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='location',
            field=models.CharField(default='remote', help_text='* E.g. City, Remote etc.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(help_text='*', max_length=100),
        ),
    ]
